# Generated by Django 3.2.9 on 2021-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('localAddress', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientPhoneNumber', models.IntegerField()),
                ('productID', models.CharField(max_length=10)),
                ('deliveryAddress', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingID', models.CharField(max_length=10)),
                ('sellerID', models.CharField(max_length=10)),
                ('warehouseID', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=15)),
                ('route', models.CharField(max_length=30)),
                ('paymentStatus', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clientPhoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riderID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('warehouseID', models.CharField(max_length=10)),
                ('productID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerID', models.CharField(max_length=10)),
                ('productID', models.CharField(max_length=10)),
                ('weightPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliveryPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sellerPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseID', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
